apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitor
  name: monitor
spec:
  ports:
  - name: metric-api
    nodePort: 30000
    port: 8080
  - name: profile-api
    nodePort: 30070
    port: 8070
  selector:
    app: monitor
  type: NodePort
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: monitor-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/monitor"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitor-pv-claim
  labels:
    app: monitor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      nodeSelector:
        kubernetes.io/hostname: repchain-node1
      containers:
      - name: monitor
        image: monitor:0.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: metric-api
        - containerPort: 8070
          name: profile-api
        volumeMounts:
        - mountPath: /var/log/monitor
          name: monitor-pv-storage
        - name: host-time
          mountPath: /etc/localtime
      volumes:
      - name: monitor-pv-storage
        persistentVolumeClaim:
          claimName: monitor-pv-claim
      - name: host-time
        hostPath:
          path: /etc/localtime
